services:
    flask:
        build: ./flask_service
        restart: on-failure
        ports:
            - "5000-5004:5000"
    aiohttp:
        build: ./aiohttp_service
        restart: on-failure
        ports:
            -  "8080:8080"
        depends_on:
            -   flask